#!/bin/bash

# Running these commands will provide C++14 support under CentOS 7:
# yum install centos-release-scl
# scl enable devtoolset-7 bash

rm -f poker

# This is my preferred compiler invocation. However, this has been seen in some
# cases to generate incorrect code. If this happens, try less aggressive optimization.
g++ -std=c++14 -pthread -Wall -Wpedantic -Wextra -Ofast -I . -I ../common -o poker *.cpp $LIBRARIES

exit 0
