#!/bin/bash

# Running these commands will provide C++14 support under CentOS 7:
# yum install centos-release-scl
# scl enable devtoolset-7 bash

rm -f poker

# This is my preferred compiler invocation. However, the generated executable does
# not function propery in one of my program variants. An assertion that should not
# be hit gets hit.
g++ -std=c++14 -Wall -Wpedantic -Ofast -I . -I ../common -L ../common -o poker *.cpp -lpoker_common


# Backing off from -Ofast --> -O3 --> -O2 --> -O1 also produces an executable that
# does not work for one of my program variants.
# g++ -std=c++14 -Wall -Wpedantic -O1 -I . -I ../common -L ../common -o poker *.cpp -lpoker_common


# Supposedly equivalent to -O1, but generated executable works fine.
# g++ -std=c++14 -Wall -Wpedantic -fauto-inc-dec -fbranch-count-reg -fcombine-stack-adjustments -fcompare-elim -fcprop-registers -fdce -fdefer-pop -fdelayed-branch -fdse -fforward-propagate -fguess-branch-probability -fif-conversion2 -fif-conversion -finline-functions-called-once -fipa-pure-const -fipa-profile -fipa-reference -fmerge-constants -fmove-loop-invariants -freorder-blocks -fshrink-wrap -fshrink-wrap-separate -fsplit-wide-types -fssa-backprop -fssa-phiopt -ftree-bit-ccp -ftree-ccp -ftree-ch -ftree-coalesce-vars -ftree-copy-prop -ftree-dce -ftree-dominator-opts -ftree-dse -ftree-forwprop -ftree-fre -ftree-phiprop -ftree-sink -ftree-slsr -ftree-sra -ftree-pta -ftree-ter -funit-at-a-time -fomit-frame-pointer -I . -I ../common -L ../common -o poker *.cpp -lpoker_common


# Supposedly equivalent to -O1, but without -fdelayed-branch (unsupported on my hardware)
# g++ -std=c++14 -Wall -Wpedantic -fauto-inc-dec -fbranch-count-reg -fcombine-stack-adjustments -fcompare-elim -fcprop-registers -fdce -fdefer-pop -fdse -fforward-propagate -fguess-branch-probability -fif-conversion2 -fif-conversion -finline-functions-called-once -fipa-pure-const -fipa-profile -fipa-reference -fmerge-constants -fmove-loop-invariants -freorder-blocks -fshrink-wrap -fshrink-wrap-separate -fsplit-wide-types -fssa-backprop -fssa-phiopt -ftree-bit-ccp -ftree-ccp -ftree-ch -ftree-coalesce-vars -ftree-copy-prop -ftree-dce -ftree-dominator-opts -ftree-dse -ftree-forwprop -ftree-fre -ftree-phiprop -ftree-sink -ftree-slsr -ftree-sra -ftree-pta -ftree-ter -funit-at-a-time -fomit-frame-pointer -I . -I ../common -L ../common -o poker *.cpp -lpoker_common

exit 0
