#!/bin/bash

# Running these commands will provide C++14 support under CentOS 7:
# yum install centos-release-scl
# scl enable devtoolset-7 bash

rm -f poker
g++ -std=c++14 -pthread -Wall -Wpedantic -Ofast -D USE_TABLE -I . -I ../common -L ../common -o poker *.cpp -lpoker_common

exit 0
