#!/bin/bash

# Running these commands will provide C++14 support under CentOS 7:
# yum install centos-release-scl
# scl enable devtoolset-7 bash

# This is needed only if common has any .cpp files.
# declare -r LIBRARIES="-L ../common -lpoker_common"

rm -f poker
g++ -std=c++14 -pthread -Wall -Wpedantic -Wextra -Ofast -D USE_LOOKUP_TABLE -I . -I ../common -o poker *.cpp $LIBRARIES

exit 0
