#!/bin/bash

# Running these commands will provide C++14 support under CentOS 7:
# yum install centos-release-scl
# scl enable devtoolset-7 bash

echo "Attempting build with C++14"

if g++ -std=c++14 -Wall -Wpedantic -Ofast -o poker *.cpp; then
   echo "Success"
   echo ""

   exit 0
fi

echo "Failure"
echo ""

echo "Attempting build with C++11"

if g++ -std=c++11 -Wall -Wpedantic -Ofast -o poker *.cpp; then
   echo "Success"
   echo ""

   exit 0
fi

echo "Failure"
echo ""

exit 1
