#!/bin/bash

# Running these commands will provide C++14 support under CentOS 7:
# yum install centos-release-scl
# scl enable devtoolset-7 bash

rm -f *.a
g++ -std=c++14 -Wall -Wpedantic -Ofast -c *.cpp
ar cru libpoker_common.a *.o
rm -f *.o

exit 0
